version: '3.4'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    expose:
#      <hostPort>:<containerPort>
      - 8080:49612
    environment:
      SPRING_PROFILES_ACTIVE: "production"
      SPRING_DATASOURCE_PASSWORD: ${DB_USER_SECRET}
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/${MYSQL_DB}?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true"



  db:
    image: mariadb/server
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DB}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD : ${DB_USER_SECRET}
