- name: Install Mysql in the server
  package:
    name: mariadb-server
    state: latest

- name: create mysql config
    template: src="my.cnf" dest="{{ mysql_cnfpath }}" mode=0644
    notify:
      - restart mysql service