- name: Install java 11 if not present on ubuntu
  apt: openjdk-11-jdk
  state: present
  when: ansible_distribution ="ubuntu"
  become: yes
- name: Set JAVA_HOME if not configured
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home




