- name: Ensure git is installed
  package:
    name: git
    state: present

- name: Pull latest  updates for the website
    git:
      repo: {{app_repo}}
      dest: {{app_dir}}
    become: True

- name: Package the application
  shell:
    chdir: {{app_dir}}
    cmd: "./mvnw -DskipTests package"

- name: create user group for the app user
  group:
    name: {{app_user_group}}

- name: create user for the application
  user:
    name: {{hr_user}}
    state: present
    system: yes
    create_home: no
    group: {{app_user_group}}

- name: Start the application


