  {{- $name := include "hr-app.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  $name }}
  labels:
    app: {{ .Chart.Name }}
    tier: frontend
    group: hr
spec:
  replicas: {{ .Values.hr_deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-web
    spec:
      containers:
        - name: {{ .Chart.Name }}-web
          image: {{ .Values.hr_deployment.image}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.hr_deployment.port }}
              name: http
              protocol: TCP
          env:
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SERVER_PORT
              value: {{ .Values.hr_deployment.port | quote }}
            - name: SPRING_PROFILES_ACTIVE
              value: production
            - name:  SPRING_LIQUIBASE_ENABLED
              value: "false"
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.hr_deployment.databasePassword }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.hr_deployment.databaseUserName }}
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://{{ .Values.hr_deployment.databaseHost }}/{{ .Values.hr_deployment.tenantName }}_hr?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true"
            - name: AWS_ACCESS_KEY_ID
              value: AKIASNPQTJPGLJRHTQAR
            - name: AWS_SECRET_ACCESS_KEY
              value: 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
            - name: AWS_REGION
              value: us-east-2
