apiVersion: v1
kind: Secret
metadata:
  name: hr-app-secrets
data:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.hr_deployment.databasePassword | b64enc }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.hr_deployment.databaseUserName | b64enc }}