- name: Update the apt package index and install packages to allow apt to use a repository over HTTPS
  package:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg
    - lsb-release
  tags:
    - docker
- name: Add Docker’s official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: set up the stable repository
  shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: install docker engine
  package:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: install docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.27.3/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 755
- name: Copy docker compose file to app directory
  copy:
    src: docker-compose-prod.yml
    dest: ~/hr_app/docker-compose-prod.yml
- name: generate .env file from .env.j2 template and copy to /hr_app/.env
  template:
    src: .env.j2
    dest: ~/hr_app/.env
- name: Run docker compose up
  shell:
    cmd: docker-compose up
    chdir: ~/hr_app

