  apiVersion: v1
  name: hr-app
  description: Employee management application written in java and vue js
  version: 1.2.3
  maintainers:
    - name: Emmanuel Ogoma
      email: ogoma.emmanuel@gmail.com
  appVersion: 1.0.0