hr_deployment:
  tenantName: default # this is the namespace to deploy application on, can be
  applicationName: hr-app
  image: mudho/hr
  port: 8080 # use any port within acceptable range
  replicaCount: 1
  serviceType: ClusterIP  # can be NodePort or LoadBalancer,
  activeProfile: production # can be production, development, staging or demo
  databasePassword: "Test"
  databaseUserName: hr_app
  databaseHost: 158.101.165.5
  awsSecretAccessKey: ''
  awsAccessKeyID: ''
  awsRegion: ''
  ingress:
    host: bettlehr.com
  tiers:
    - frontend
    - backend
    - database
  secrets:
