  apiVersion: v2
  name: Beetle-HR
  description: Employee management application written in java and vue js
  version: 1 # version of the chart
  maintainers:
    - name: Emmanuel Ogoma
      email: ogoma.emmanuel@gmail.com
  dependencies:
    - name: bitnami/redis
      version: 6.2.7
      repository: https://charts.bitnami.com/bitnami
  appVersion: 1.0.0  #version of the application being deployed using the chart
