hr_deployment:
  tenantName: default # this is the namespace to deploy application on, can be
  applicationName: hr-app
  image: mudho/hr
  port: 8080 # use any port within acceptable range
  replicaCount: 1
  serviceType: NodePort  # can be NodePort or LoadBalancer,
  activeProfile: production # can be production, development, staging or demo
  databasePassword: secret
  tiers:
    - frontend
    - backend
    - database
  databaseHost: somedbhost