name: Main Branch
defaults:
  run:
    working-directory: hr_core
on:
  push:
    branches: [ master]
#    branches: [ release ]
#  pull_request:
#    branches: [ master]
#    branches: [ release]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify
      - name: Archive jar files to be used in deploy step
        uses: actions/upload-artifact@v3
        with:
          name: hr-jars
          path: target/hr_core.0.0.1-SNAPSHOT.jar
#      - name: Set up Java for publishing to Maven Central Repository
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.11
#      - name: Publish to GitHub Packages
#        env:
#          GITHUB_TOKEN: ${{ secrets.DEPLOY }}
#        run: mvn -B clean deploy -DskipTests
  docker:
    needs: test
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:hr_core"
          push: true
          tags: mudho/hr:latest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy to oracle compute vm
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: hr-jars
      - uses: actions/checkout@v2
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: target/hr_core.0.0.1-SNAPSHOT.jar
          remote_path: /opt/my-application.jar
          remote_host: ${{ secrets.ORACLE_COMPUTE_HOST_817 }}
          remote_user: opc
          remote_key: ${{ secrets.ORACLE_COMPUTE_817_DEPLOY_KEY }}