name: Main Branch

on:
  push:
#    branches: [ master,eogoma ]
    branches: [ release ]
  pull_request:
#    branches: [ master]
    branches: [ release]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify
#      - name: Set up Java for publishing to Maven Central Repository
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.11
#      - name: Publish to GitHub Packages
#        env:
#          GITHUB_TOKEN: ${{ secrets.DEPLOY }}
#        run: mvn -B clean deploy -DskipTests
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: mudho/hr
          tag_with_ref: true