name: Main Branch

on:
  push:
    branches: [ master,eogoma ]
  pull_request:
    branches: [ master]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY }}
        run: mvn -B clean deploy -DskipTests
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build the Docker image
        run: docker build -t hr:latest .
      - name: Tag the Docker image
        run: docker tag hr:latest hr:1.0
      - name: Push the Docker image to the registry
        run: docker push hr:1.0