name: Main Branch
defaults:
  run:
    working-directory: hr_core
on:
  push:
    branches: [ master]
#    branches: [ release ]
#  pull_request:
#    branches: [ master]
#    branches: [ release]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify
#      - name: Set up Java for publishing to Maven Central Repository
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.11
#      - name: Publish to GitHub Packages
#        env:
#          GITHUB_TOKEN: ${{ secrets.DEPLOY }}
#        run: mvn -B clean deploy -DskipTests
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          context: "{{defaultContext}}:hr_core"
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          dockerfile: hr_core/Dockerfile
          repository: mudho/hr
          tag_with_ref: true